name: Clickable Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Parse version
        run: |
          echo ARTIFACT_VERSION=$(cat prebuild.sh | grep "export REPO_VERSION=" | awk -F'"' '$0=$2')$(cat prebuild.sh | grep "export CLICK_VERSION_PREFIX=" | awk -F'"' '$0=$2') >> $GITHUB_ENV
      - name: Install clickable
        run: |
          python3 -m pip install clickable-ut
      - name: Build
        run: |
          clickable build --arch ${{ matrix.arch }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cinny.nitanmarcel_${{ env.ARTIFACT_VERSION }}_${{ matrix.arch }}
          path: build/*/app/*.click
          if-no-files-found: error
